Repository Striveworks/valor, pull requests merged in 2024-10, with the labels that each got.

#774 Add as_dict to object detection
  lite/tests/detection/test_average_precision.py
  lite/tests/detection/test_average_recall.py
  lite/tests/detection/test_confusion_matrix.py
  lite/tests/detection/test_counts.py
  lite/tests/detection/test_pr_curve.py
  lite/tests/detection/test_precision.py
  lite/tests/detection/test_recall.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/detection/manager.py
Labels: feature request

#775 Remove label keys from `lite` detections
  integration_tests/benchmarks/classification/benchmark_script.py
  integration_tests/benchmarks/object-detection/benchmark_script.py
  lite/tests/detection/conftest.py
  lite/tests/detection/test_average_precision.py
  lite/tests/detection/test_average_recall.py
  lite/tests/detection/test_confusion_matrix.py
  lite/tests/detection/test_counts.py
  lite/tests/detection/test_dataloader.py
  lite/tests/detection/test_evaluator.py
  lite/tests/detection/test_filtering.py
  lite/tests/detection/test_pr_curve.py
  lite/tests/detection/test_precision.py
  lite/tests/detection/test_recall.py
  lite/tests/detection/test_schemas.py
  lite/tests/detection/test_stability.py
  lite/valor_lite/detection/annotation.py
  lite/valor_lite/detection/computation.py
  lite/valor_lite/detection/manager.py
  lite/valor_lite/detection/metric.py
Labels: enhancement

#776 Remove label keys from `lite` classification
  lite/tests/classification/conftest.py
  lite/tests/classification/test_accuracy.py
  lite/tests/classification/test_confusion_matrix.py
  lite/tests/classification/test_counts.py
  lite/tests/classification/test_dataloader.py
  lite/tests/classification/test_evaluator.py
  lite/tests/classification/test_f1.py
  lite/tests/classification/test_filtering.py
  lite/tests/classification/test_precision.py
  lite/tests/classification/test_recall.py
  lite/tests/classification/test_rocauc.py
  lite/tests/classification/test_schemas.py
  lite/tests/classification/test_stability.py
  lite/valor_lite/classification/annotation.py
  lite/valor_lite/classification/computation.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/classification/metric.py
Labels: enhancement

#777 Enforce Single Groundtruth in Lite
  lite/tests/classification/conftest.py
  lite/tests/classification/test_dataloader.py
  lite/tests/classification/test_filtering.py
  lite/tests/classification/test_schemas.py
  lite/tests/classification/test_stability.py
  lite/tests/detection/test_schemas.py
  lite/tests/detection/test_stability.py
  lite/valor_lite/classification/annotation.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/detection/annotation.py
Labels: improvement

#728 Add Retries for LLM-Guided Metrics
  api/tests/functional-tests/backend/core/test_llm_clients.py
  api/valor_api/backend/core/llm_clients.py
  api/valor_api/backend/metrics/text_generation.py
  core/tests/functional-tests/test_llm_clients.py
  core/tests/functional-tests/test_text_generation.py
  core/valor_core/llm_clients.py
  core/valor_core/text_generation.py
Labels: feature

#773 Lite Semantic Segmentation
  .github/workflows/lite-tests-and-coverage.yml
  lite/tests/__init__.py
  lite/tests/classification/__init__.py
  lite/tests/segmentation/__init__.py
  lite/tests/segmentation/conftest.py
  lite/tests/segmentation/test_accuracy.py
  lite/tests/segmentation/test_annotation.py
  lite/tests/segmentation/test_confusion_matrix.py
  lite/tests/segmentation/test_dataloader.py
  lite/tests/segmentation/test_evaluator.py
  lite/tests/segmentation/test_f1.py
  lite/tests/segmentation/test_filtering.py
  lite/tests/segmentation/test_iou.py
  lite/tests/segmentation/test_precision.py
  lite/tests/segmentation/test_recall.py
  lite/tests/segmentation/test_stability.py
  lite/valor_lite/segmentation/__init__.py
  lite/valor_lite/segmentation/annotation.py
  lite/valor_lite/segmentation/computation.py
  lite/valor_lite/segmentation/manager.py
  lite/valor_lite/segmentation/metric.py
Labels: feature

#778 Performance Bugfixes
  lite/tests/detection/conftest.py
  lite/tests/detection/test_dataloader.py
  lite/tests/detection/test_filtering.py
  lite/tests/detection/test_iou.py
  lite/tests/detection/test_schemas.py
  lite/valor_lite/classification/computation.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/detection/annotation.py
  lite/valor_lite/detection/computation.py
  lite/valor_lite/detection/manager.py
Labels: improvement

#785 Boundiing Box Examples as dict
  lite/tests/detection/test_confusion_matrix.py
  lite/valor_lite/detection/manager.py
  lite/valor_lite/detection/metric.py
Labels: feature request

#790 Fix Example Notebooks in Lite
  lite/examples/object-detection.ipynb
  lite/examples/tabular_classification.ipynb
Labels: bug

#791 Tweak Segmentation Testing
  lite/tests/semantic_segmentation/conftest.py
  lite/tests/semantic_segmentation/test_evaluator.py
Labels: bug

#788 Remove `metrics_to_return`
  lite/benchmarks/benchmark_classification.py
  lite/benchmarks/benchmark_objdet.py
  lite/examples/object-detection.ipynb
  lite/examples/tabular_classification.ipynb
  lite/tests/classification/test_confusion_matrix.py
  lite/tests/object_detection/test_average_precision.py
  lite/tests/object_detection/test_average_recall.py
  lite/tests/object_detection/test_confusion_matrix.py
  lite/tests/object_detection/test_evaluator.py
  lite/tests/object_detection/test_filtering.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/classification/metric.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/object_detection/metric.py
  lite/valor_lite/semantic_segmentation/manager.py
Labels: improvement

#794 Lite Shouldnt Return Numpy Types in metrics
  lite/tests/classification/test_evaluator.py
  lite/tests/object_detection/test_evaluator.py
  lite/tests/semantic_segmentation/test_evaluator.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/semantic_segmentation/manager.py
Labels: bug

#796 Add `scores` to `PrecisionRecallCurve`
  lite/benchmarks/benchmark_classification.py
  lite/benchmarks/benchmark_objdet.py
  lite/examples/object-detection.ipynb
  lite/tests/object_detection/test_pr_curve.py
  lite/valor_lite/object_detection/computation.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/object_detection/metric.py
Labels: feature request

#797 fix objdet confusion matrix OOM
  lite/tests/object_detection/test_stability.py
  lite/valor_lite/object_detection/computation.py
Labels: bug, improvement

#798 Lite Classification Accuracy Fix
  lite/tests/classification/test_accuracy.py
  lite/valor_lite/classification/computation.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/classification/metric.py
Labels: bug

#801 Lite ObjDet Accuracy Fix
  lite/tests/object_detection/test_accuracy.py
  lite/tests/object_detection/test_average_precision.py
  lite/tests/object_detection/test_average_recall.py
  lite/tests/object_detection/test_pr_curve.py
  lite/valor_lite/object_detection/computation.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/object_detection/metric.py
Labels: bug

#803 Lite Unify Metric Formatting
  .github/workflows/build-and-publish.yml
  lite/benchmarks/benchmark_classification.py
  lite/examples/object-detection.ipynb
  lite/examples/tabular_classification.ipynb
  lite/tests/classification/test_accuracy.py
  lite/tests/classification/test_confusion_matrix.py
  lite/tests/classification/test_counts.py
  lite/tests/classification/test_evaluator.py
  lite/tests/classification/test_f1.py
  lite/tests/classification/test_filtering.py
  lite/tests/classification/test_precision.py
  lite/tests/classification/test_recall.py
  lite/tests/classification/test_rocauc.py
  lite/tests/object_detection/test_accuracy.py
  lite/tests/object_detection/test_average_precision.py
  lite/tests/object_detection/test_average_recall.py
  lite/tests/object_detection/test_confusion_matrix.py
  lite/tests/object_detection/test_counts.py
  lite/tests/object_detection/test_evaluator.py
  lite/tests/object_detection/test_pr_curve.py
  lite/tests/object_detection/test_precision.py
  lite/tests/object_detection/test_recall.py
  lite/tests/semantic_segmentation/test_accuracy.py
  lite/tests/semantic_segmentation/test_confusion_matrix.py
  lite/tests/semantic_segmentation/test_evaluator.py
  lite/tests/semantic_segmentation/test_f1.py
  lite/tests/semantic_segmentation/test_iou.py
  lite/tests/semantic_segmentation/test_precision.py
  lite/tests/semantic_segmentation/test_recall.py
  lite/valor_lite/classification/__init__.py
  lite/valor_lite/classification/computation.py
  lite/valor_lite/classification/manager.py
  lite/valor_lite/classification/metric.py
  lite/valor_lite/classification/utilities.py
  lite/valor_lite/object_detection/__init__.py
  lite/valor_lite/object_detection/computation.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/object_detection/metric.py
  lite/valor_lite/object_detection/utilities.py
  lite/valor_lite/schemas.py
  lite/valor_lite/semantic_segmentation/__init__.py
  lite/valor_lite/semantic_segmentation/computation.py
  lite/valor_lite/semantic_segmentation/manager.py
  lite/valor_lite/semantic_segmentation/metric.py
  lite/valor_lite/semantic_segmentation/utilities.py
Labels: improvement

#802 Migrate Text Generation Metrics to valor-lite
  .github/workflows/core-benchmark-evaluations.yml
  .github/workflows/core-tests-and-coverage.yml
  .github/workflows/lite-tests-and-coverage.yml
  Makefile
  lite/examples/text_generation.ipynb
  lite/pyproject.toml
  lite/tests/classification/test_metric.py
  lite/tests/object_detection/test_metric.py
  lite/tests/semantic_segmentation/test_metric.py
  lite/tests/text_generation/conftest.py
  lite/tests/text_generation/llm/__init__.py
  lite/tests/text_generation/llm/test_generation.py
  lite/tests/text_generation/llm/test_integrations.py
  lite/tests/text_generation/llm/test_utilities.py
  lite/tests/text_generation/llm/test_validators.py
  lite/tests/text_generation/metrics/test_answer_correctness.py
  lite/tests/text_generation/metrics/test_answer_relevance.py
  lite/tests/text_generation/metrics/test_bias.py
  lite/tests/text_generation/metrics/test_context_precision.py
  lite/tests/text_generation/metrics/test_context_recall.py
  lite/tests/text_generation/metrics/test_context_relevance.py
  lite/tests/text_generation/metrics/test_faithfulness.py
  lite/tests/text_generation/metrics/test_hallucination.py
  lite/tests/text_generation/metrics/test_metric.py
  lite/tests/text_generation/metrics/test_rouge.py
  lite/tests/text_generation/metrics/test_sentence_bleu.py
  lite/tests/text_generation/metrics/test_summary_coherence.py
  lite/tests/text_generation/metrics/test_toxicity.py
  lite/tests/text_generation/test_evaluator.py
  lite/tests/text_generation/test_manager.py
  lite/valor_lite/classification/metric.py
  lite/valor_lite/object_detection/manager.py
  lite/valor_lite/object_detection/metric.py
  lite/valor_lite/schemas.py
  lite/valor_lite/semantic_segmentation/metric.py
  lite/valor_lite/text_generation/__init__.py
  lite/valor_lite/text_generation/annotation.py
  lite/valor_lite/text_generation/computation.py
  lite/valor_lite/text_generation/llm/__init__.py
  lite/valor_lite/text_generation/llm/exceptions.py
  lite/valor_lite/text_generation/llm/generation.py
  lite/valor_lite/text_generation/llm/instructions.py
  lite/valor_lite/text_generation/llm/integrations.py
  lite/valor_lite/text_generation/llm/utilities.py
  lite/valor_lite/text_generation/llm/validators.py
  lite/valor_lite/text_generation/manager.py
  lite/valor_lite/text_generation/metric.py
Labels: feature
