Repository Striveworks/valor, pull requests merged in 2024-08, with the labels that each got.

#714 Fix Filter Docs
  client/valor/schemas/filters.py
  client/valor/schemas/symbolic/operators.py
  docs/client_api/core/Annotation.md
  docs/client_api/core/Client.md
  docs/client_api/core/Dataset.md
  docs/client_api/core/Datum.md
  docs/client_api/core/Evaluation.md
  docs/client_api/core/Groundtruth.md
  docs/client_api/core/Label.md
  docs/client_api/core/Model.md
  docs/client_api/core/Prediction.md
  docs/client_api/core/Viz.md
  docs/client_api/filtering/Conditions/Contains.md
  docs/client_api/filtering/Conditions/Gt.md
  docs/client_api/filtering/Conditions/Gte.md
  docs/client_api/filtering/Conditions/Inside.md
  docs/client_api/filtering/Conditions/Intersects.md
  docs/client_api/filtering/Conditions/IsNotNull.md
  docs/client_api/filtering/Conditions/IsNull.md
  docs/client_api/filtering/Conditions/Lt.md
  docs/client_api/filtering/Conditions/Lte.md
  docs/client_api/filtering/Conditions/Ne.md
  docs/client_api/filtering/Conditions/Outside.md
  docs/client_api/filtering/Filter.md
  docs/client_api/filtering/Logic/And.md
  docs/client_api/filtering/Logic/Not.md
  docs/client_api/filtering/Logic/Or.md
  docs/client_api/schemas/Evaluation/EvaluationParameters.md
  docs/client_api/schemas/Spatial/Box.md
  docs/client_api/schemas/Spatial/LineString.md
  docs/client_api/schemas/Spatial/MultiLineString.md
  docs/client_api/schemas/Spatial/MultiPoint.md
  docs/client_api/schemas/Spatial/MultiPolygon.md
  docs/client_api/schemas/Spatial/Point.md
  docs/client_api/schemas/Spatial/Polygon.md
  docs/client_api/schemas/Spatial/Raster.md
  docs/index.md
  docs/metadata_and_filtering.md
  mkdocs.yml
Labels: documentation

#651 Implement `valor_core` to compute metrics locally via numpy
  .github/workflows/client-api-benchmark-evaluations.yml
  .github/workflows/client-api-tests-and-coverage.yml
  .github/workflows/core-benchmark-evaluations.yml
  .github/workflows/core-tests-and-coverage.yml
  .pre-commit-config.yaml
  core/LICENSE
  core/README.md
  core/benchmarks/.gitignore
  core/benchmarks/classification/benchmark_script.py
  core/benchmarks/object-detection/benchmark_script.py
  core/examples/.gitignore
  core/examples/getting_started.ipynb
  core/pyproject.toml
  core/tests/conftest.py
  core/tests/functional-tests/test_classification.py
  core/tests/functional-tests/test_detection.py
  core/tests/functional-tests/test_detection_manager.py
  core/tests/unit-tests/test_geometry.py
  core/tests/unit-tests/test_metrics.py
  core/tests/unit-tests/test_schemas.py
  core/tests/unit-tests/test_utilities.py
  core/valor_core/__init__.py
  core/valor_core/classification.py
  core/valor_core/detection.py
  core/valor_core/enums.py
  core/valor_core/geometry.py
  core/valor_core/managers.py
  core/valor_core/metrics.py
  core/valor_core/schemas.py
  core/valor_core/utilities.py
Labels: feature

#717 Fix PR Curve FP Count
  api/valor_api/backend/metrics/detection.py
  integration_tests/client/metrics/test_detection.py
Labels: bug

#718 Add test_evaluate_detection_fp to `valor_core`
  core/tests/functional-tests/test_detection.py
Labels: bug

#719 Fix bug when assigning "no prediction" false negative flags
  core/tests/functional-tests/test_classification.py
  core/valor_core/classification.py
Labels: bug

#723 Fix DetailedPR bug for classification
  core/tests/conftest_outputs.py
  core/tests/functional-tests/test_classification.py
  core/valor_core/classification.py
  core/valor_core/managers.py
Labels: bug

#727 Unaccounted Time in Valor-Core Benchmark
  .github/workflows/core-benchmark-evaluations.yml
  core/benchmarks/object-detection/benchmark_core.py
  core/benchmarks/object-detection/benchmark_manager.py
Labels: bug

#729 Update API Benchmarks
  integration_tests/benchmarks/object-detection/benchmark_script.py
Labels: improvement

#731 Vectorize IOU calcs for axis-aligned bboxes
  core/pyproject.toml
  core/valor_core/detection.py
  core/valor_core/geometry.py
Labels: improvement
