Repository Striveworks/valor, pull requests merged in 2024-07, with the labels that each got.

#645 Fix `validate_matching_label_keys`
  api/valor_api/backend/core/evaluation.py
Labels: bug

#643 Fixed Bulk Add `DatumAlreadyExistsError` and `AnnotationAlreadyExistsError`
  client/valor/client.py
  client/valor/coretypes.py
  integration_tests/client/test_client.py
Labels: bug

#637 Fix Classification Performance
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/valor_api/backend/core/prediction.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/crud/_create.py
Labels: bug

#638 Add benchmarking workflow to evaluate classification and OD runtimes
  .github/workflows/benchmark-evaluations.yml
  .github/workflows/stress-test.yml
  integration_tests/benchmarks/.gitignore
  integration_tests/benchmarks/classification/benchmark_script.py
  integration_tests/benchmarks/object-detection/benchmark_script.py
  integration_tests/stress_test.py
Labels: enhancement

#660 Expanded Client Timeout Controls
  client/unit-tests/test_client.py
  client/unit-tests/test_coretypes.py
  client/valor/client.py
  client/valor/coretypes.py
  integration_tests/client/test_client.py
Labels: improvement

#664 Allow Retrying of Deletion
  api/valor_api/backend/core/dataset.py
  api/valor_api/backend/core/model.py
  integration_tests/client/test_client.py
Labels: bug, improvement

#668 Metric Ingestion Patch
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/backend/metrics/segmentation.py
Labels: improvement

#569 Add text generation task type
  .github/workflows/tests-and-coverage.yml
  .pre-commit-config.yaml
  Makefile
  api/Dockerfile
  api/pyproject.toml
  api/tests/functional-tests/backend/core/test_llm_clients.py
  api/tests/functional-tests/backend/metrics/test_text_generation.py
  api/tests/unit-tests/backend/metrics/test_metric_utils.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/schemas/test_metrics.py
  api/valor_api/backend/__init__.py
  api/valor_api/backend/core/annotation.py
  api/valor_api/backend/core/datum.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/core/groundtruth.py
  api/valor_api/backend/core/llm_clients.py
  api/valor_api/backend/core/prediction.py
  api/valor_api/backend/metrics/__init__.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/backend/metrics/text_generation.py
  api/valor_api/backend/models.py
  api/valor_api/backend/query/solvers.py
  api/valor_api/crud/_create.py
  api/valor_api/enums.py
  api/valor_api/exceptions.py
  api/valor_api/schemas/__init__.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/metrics.py
  api/valor_api/schemas/types.py
  client/unit-tests/coretypes/test_core.py
  client/unit-tests/test_typing.py
  client/valor/coretypes.py
  client/valor/enums.py
  client/valor/schemas/__init__.py
  client/valor/schemas/evaluation.py
  client/valor/schemas/symbolic/collections.py
  client/valor/schemas/symbolic/types.py
  docs/metrics.md
  examples/.gitignore
  examples/text-generation/content_generation_data.csv
  examples/text-generation/rag_data.csv
  examples/text-generation/summarization_data.csv
  examples/text-generation/text_generation.ipynb
  integration_tests/benchmarks/object-detection/benchmark_script.py
  integration_tests/client/datasets/test_groundtruth.py
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_text_generation_with_mock_client.py
  integration_tests/external/test_text_generation_no_mock.py
  migrations/sql/00000012_add_datum_text.down.sql
  migrations/sql/00000012_add_datum_text.up.sql
Labels: feature

#684 Fixed Average-Precision Integration Error
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/valor_api/backend/metrics/detection.py
Labels: bug
