Repository Striveworks/valor, pull requests merged in 2024-03, with the labels that each got.

#437 pgvector datum embeddings
  .github/workflows/api-docker.yml
  .github/workflows/pg-docker.yml
  .github/workflows/stress-test.yml
  .github/workflows/tests-and-coverage.yml
  .pre-commit-config.yaml
  Makefile
  api/pyproject.toml
  api/tests/functional-tests/backend/core/test_annotation.py
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/core/test_model.py
  api/tests/functional-tests/backend/metrics/test_metric_utils.py
  api/tests/functional-tests/conftest.py
  api/tests/unit-tests/schemas/test_core.py
  api/valor_api/backend/core/annotation.py
  api/valor_api/backend/models.py
  api/valor_api/enums.py
  api/valor_api/schemas/__init__.py
  api/valor_api/schemas/core.py
  client/valor/coretypes.py
  client/valor/data_generation.py
  client/valor/enums.py
  database/Dockerfile
  docker-compose.cicd-override.yml
  docker-compose.yml
  docs/contributing.md
  docs/index.md
  integration_tests/client/datatype/test_annotation_types.py
  migrations/entrypoint.sh
  migrations/sql/00000001_initialize_schema.up.sql
Labels: feature

#460 Add Average Recall to OD metrics
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/unit-tests/backend/metrics/test_detection.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/schemas/__init__.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/metrics.py
  client/valor/coretypes.py
  client/valor/schemas/evaluation.py
  docs/metrics.md
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/filtering/test_geospatial_filtering.py
  integration_tests/client/metrics/test_detection.py
Labels: documentation, enhancement

#481 Disallow mismatched ground truth / prediction label keys for classification tasks
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/__init__.py
  api/valor_api/backend/core/__init__.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/core/label.py
  api/valor_api/backend/metrics/classification.py
  client/valor/coretypes.py
  examples/tabular_classification.ipynb
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/models/test_model.py
  integration_tests/conftest.py
Labels: bug

#486 Implement quick follow-ups on precision-recall curve PR
  api/tests/unit-tests/backend/metrics/test_detection.py
  api/valor_api/backend/metrics/detection.py
  docs/metrics.md
  migrations/sql/00000001_initialize_schema.up.sql
  migrations/sql/00000002_alter_metric_value_type.down.sql
  migrations/sql/00000002_alter_metric_value_type.up.sql
Labels: documentation, improvement

#489 Improve test coverage to 90% and enforce coverage check in `combine-coverage-report` workflow
  .github/workflows/tests-and-coverage.yml
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/backend/metrics/test_segmentation.py
  client/unit-tests/coretypes/test_core.py
  client/unit-tests/test_client.py
  client/valor/client.py
Labels: bug

#492 Fix typing errors in tests
  .pre-commit-config.yaml
  api/tests/functional-tests/backend/core/test_annotation.py
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_geometry.py
  api/tests/functional-tests/backend/core/test_label.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/backend/metrics/test_segmentation.py
  api/tests/functional-tests/backend/query/test_ops.py
  api/tests/functional-tests/conftest.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/functional-tests/crud/test_read.py
  api/tests/functional-tests/schemas/test_raster.py
  api/tests/unit-tests/backend/metrics/test_detection.py
  api/tests/unit-tests/backend/metrics/test_mot.py
  api/tests/unit-tests/backend/query/test_filtering.py
  api/tests/unit-tests/conftest.py
  api/tests/unit-tests/schemas/test_auth.py
  api/tests/unit-tests/schemas/test_core.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/schemas/test_geometry_schema.py
  api/tests/unit-tests/schemas/test_info.py
  api/tests/unit-tests/schemas/test_label.py
  api/tests/unit-tests/schemas/test_metrics.py
  api/tests/unit-tests/test_enums.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/geometry.py
  client/unit-tests/coretypes/test_core.py
  client/unit-tests/coretypes/test_filtering.py
  client/unit-tests/schemas/test_filters.py
  integration_tests/client/datasets/test_dataset.py
  integration_tests/client/datasets/test_datum.py
  integration_tests/client/datasets/test_groundtruth.py
  integration_tests/client/datatype/test_annotation_types.py
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/datatype/test_geometry.py
  integration_tests/client/filtering/test_geometric_filtering.py
  integration_tests/client/filtering/test_geospatial_filtering.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_segmentation.py
  integration_tests/client/models/test_model.py
  integration_tests/client/models/test_prediction.py
  integration_tests/client/test_client.py
  integration_tests/conftest.py
  pyrightconfig.json
  utils/.gitignore
  utils/README.md
  utils/__init__.py
  utils/analyze_profiling_data.ipynb
  utils/requirements.txt
  utils/run_profile.py
  utils/viz.py
Labels: testing
