Repository Striveworks/valor, pull requests merged in 2024-04, with the labels that each got.

#516 BugFix: PrecisionRecallCurve Datum UID
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/unit-tests/backend/metrics/test_detection.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/schemas/metrics.py
  integration_tests/client/metrics/test_classification.py
Labels: bug

#510 Fix `make dev-env` for Mac M1/M2 users
  .pre-commit-config.yaml
  api/Dockerfile
  api/pyproject.toml
  api/tests/unit-tests/backend/metrics/test_mot.py
  api/valor_api/backend/metrics/multi_object_tracking.py
Labels: bug

#517 Add parameters to TS client
  api/valor_api/backend/metrics/detection.py
  api/valor_api/schemas/evaluation.py
  ts-client/src/ValorClient.ts
  ts-client/tests/ValorClient.test.ts
Labels: bug, enhancement

#519 Fix TS tests by lengthening timeouts
  ts-client/tests/ValorClient.test.ts
Labels: bug

#530 Add pagination for `GET` endpoints
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_datum.py
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/core/test_label.py
  api/tests/functional-tests/backend/core/test_model.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/functional-tests/crud/test_read.py
  api/tests/unit-tests/test_main.py
  api/valor_api/api_utils.py
  api/valor_api/backend/__init__.py
  api/valor_api/backend/core/__init__.py
  api/valor_api/backend/core/dataset.py
  api/valor_api/backend/core/datum.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/core/label.py
  api/valor_api/backend/core/model.py
  api/valor_api/crud/_read.py
  api/valor_api/main.py
  integration_tests/client/datasets/test_dataset.py
  integration_tests/client/filtering/test_geospatial_filtering.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/test_client.py
Labels: enhancement

#551 Fix broken build after #511
  docs/client_api/Schemas/Geometries.md
Labels: bug

#546 Add basic analytics to the evaluation table
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/core/test_model.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/backend/metrics/test_metric_utils.py
  api/tests/functional-tests/backend/metrics/test_segmentation.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/backend/metrics/segmentation.py
  api/valor_api/backend/models.py
  api/valor_api/schemas/evaluation.py
  client/unit-tests/coretypes/test_evaluation.py
  client/unit-tests/schemas/test_evaluation_schemas.py
  client/valor/coretypes.py
  client/valor/schemas/evaluation.py
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_segmentation.py
  migrations/sql/00000006_add_evaluation_metadata.down.sql
  migrations/sql/00000006_add_evaluation_metadata.up.sql
  ts-client/src/ValorClient.ts
Labels: enhancement
