Repository Striveworks/valor, pull requests merged in 2024-09, with the labels that each got.

#733 Fix GitHub workflows
  .github/workflows/client-api-tests-and-coverage.yml
Labels: bug

#740 Fix bug in `valor_core` where some true positives weren't being correctly deassigned
  core/tests/conftest_inputs.py
  core/tests/conftest_outputs.py
  core/tests/functional-tests/test_detection.py
  core/tests/functional-tests/test_detection_manager.py
  core/valor_core/detection.py
Labels: bug

#744 Fix DetailedPRCurve examples for classification tasks
  core/tests/conftest_inputs.py
  core/tests/conftest_outputs.py
  core/tests/functional-tests/test_classification.py
  core/valor_core/classification.py
Labels: bug

#755 bugfix for ranked pairing in lite
  lite/tests/detection/conftest.py
  lite/tests/detection/test_average_precision.py
  lite/tests/detection/test_precision.py
  lite/valor_lite/detection/computation.py
Labels: bug

#761 Add Bounding Box Examples to Detailed Metrics
  lite/tests/detection/test_detailed_counts.py
  lite/tests/detection/test_schemas.py
  lite/valor_lite/detection/annotation.py
  lite/valor_lite/detection/computation.py
  lite/valor_lite/detection/manager.py
  lite/valor_lite/detection/metric.py
Labels: feature

#765 Add Metrics to return to Lite
  lite/benchmarks/benchmark_objdet.py
  lite/tests/detection/test_detailed_counts.py
  lite/tests/detection/test_evaluator.py
  lite/valor_lite/detection/manager.py
  lite/valor_lite/detection/metric.py
Labels: feature request

#759 Enable Bitmasks and Polygons in `lite`
  lite/benchmarks/benchmark_objdet.py
  lite/pyproject.toml
  lite/tests/detection/conftest.py
  lite/tests/detection/test_average_precision.py
  lite/tests/detection/test_average_recall.py
  lite/tests/detection/test_counts.py
  lite/tests/detection/test_dataloader.py
  lite/tests/detection/test_detailed_counts.py
  lite/tests/detection/test_evaluator.py
  lite/tests/detection/test_filtering.py
  lite/tests/detection/test_iou.py
  lite/tests/detection/test_pr_curve.py
  lite/tests/detection/test_precision.py
  lite/tests/detection/test_recall.py
  lite/tests/detection/test_schemas.py
  lite/tests/detection/test_stability.py
  lite/valor_lite/detection/__init__.py
  lite/valor_lite/detection/annotation.py
  lite/valor_lite/detection/computation.py
  lite/valor_lite/detection/manager.py
Labels: enhancement
