Repository Striveworks/valor, pull requests merged in 2024-06, with the labels that each got.

#595 Add `metrics_to_return` to all evaluations
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/metrics.py
  client/valor/coretypes.py
  client/valor/schemas/evaluation.py
  docs/metrics.md
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_segmentation.py
  ts-client/src/ValorClient.ts
  ts-client/tests/ValorClient.test.ts
Labels: enhancement

#599 Fix coco notebook
  examples/object-detection/coco-yolo.ipynb
  examples/object-detection/integrations/coco_integration.py
Labels: bug

#589 Remove `task_type` from `Annotation`; users should use `is_instance_segmentation=True` to denote instance segmentations
  api/tests/functional-tests/backend/core/test_annotation.py
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/core/test_geometry.py
  api/tests/functional-tests/backend/core/test_label.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/backend/query/test_ops.py
  api/tests/functional-tests/conftest.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/functional-tests/crud/test_evaluation_crud.py
  api/tests/functional-tests/crud/test_read.py
  api/tests/functional-tests/crud/test_update.py
  api/tests/unit-tests/conftest.py
  api/tests/unit-tests/schemas/test_core.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/core/__init__.py
  api/valor_api/backend/core/annotation.py
  api/valor_api/backend/core/dataset.py
  api/valor_api/backend/core/geometry.py
  api/valor_api/backend/models.py
  api/valor_api/backend/query/filtering.py
  api/valor_api/schemas/types.py
  client/unit-tests/coretypes/test_core.py
  client/unit-tests/schemas/test_filters.py
  client/unit-tests/test_typing.py
  client/unit-tests/test_viz.py
  client/valor/coretypes.py
  client/valor/schemas/symbolic/collections.py
  client/valor/viz.py
  examples/object-detection/coco-yolo.ipynb
  examples/object-detection/integrations/coco_integration.py
  examples/object-detection/integrations/yolo_integration.py
  integration_tests/client/datasets/test_dataset.py
  integration_tests/client/datasets/test_datum.py
  integration_tests/client/datasets/test_groundtruth.py
  integration_tests/client/datatype/test_annotation_types.py
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/datatype/test_geometry.py
  integration_tests/client/filtering/test_geometric_filtering.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_evaluations.py
  integration_tests/client/models/test_model.py
  integration_tests/client/models/test_prediction.py
  integration_tests/client/test_client.py
  integration_tests/client/test_exceptions.py
  integration_tests/conftest.py
  migrations/sql/00000008_replace_annotation_task_type.down.sql
  migrations/sql/00000008_replace_annotation_task_type.up.sql
  ts-client/src/ValorClient.ts
  ts-client/tests/ValorClient.test.ts
Labels: enhancement

#609 Removed `meta` from `schemas.EvaluationRequest`
  api/tests/functional-tests/backend/core/test_dataset.py
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/core/test_model.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_metric_utils.py
  api/tests/functional-tests/backend/metrics/test_segmentation.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/functional-tests/crud/test_evaluation_crud.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/schemas/evaluation.py
  client/unit-tests/schemas/test_evaluation_schemas.py
  client/valor/coretypes.py
  client/valor/schemas/evaluation.py
  ts-client/src/ValorClient.ts
Labels: improvement

#584 Simplify `PrecisionRecallCurve` and add `DetailedPrecisionRecallCurve` for advanced debugging
  api/tests/functional-tests/backend/core/test_evaluation.py
  api/tests/functional-tests/backend/metrics/test_classification.py
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/tests/functional-tests/crud/test_create_delete.py
  api/tests/functional-tests/crud/test_evaluation_crud.py
  api/tests/unit-tests/backend/metrics/test_detection.py
  api/tests/unit-tests/schemas/test_evaluation.py
  api/tests/unit-tests/test_main.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  api/valor_api/backend/metrics/metric_utils.py
  api/valor_api/backend/metrics/segmentation.py
  api/valor_api/schemas/__init__.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/metrics.py
  client/valor/coretypes.py
  client/valor/schemas/evaluation.py
  docs/metrics.md
  docs/technical_concepts.md
  integration_tests/client/datatype/test_data_generation.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/conftest.py
  ts-client/src/ValorClient.ts
  ts-client/tests/ValorClient.test.ts
Labels: bug, feature

#615 Add retry logic to avoid `request` timeouts
  client/unit-tests/coretypes/test_evaluation.py
  client/valor/client.py
  integration_tests/client/test_client.py
Labels: bug

#631 Bugfix Evaluating w/ No Predictions
  api/tests/functional-tests/backend/metrics/test_detection.py
  api/valor_api/backend/core/evaluation.py
  api/valor_api/backend/metrics/classification.py
  api/valor_api/backend/metrics/detection.py
  integration_tests/client/metrics/test_classification.py
  integration_tests/client/metrics/test_detection.py
  integration_tests/client/metrics/test_segmentation.py
Labels: bug

#632 Add text comparison metrics to Ben's PR
  .pre-commit-config.yaml
  api/Dockerfile
  api/pyproject.toml
  api/tests/functional-tests/backend/metrics/test_text_generation.py
  api/tests/unit-tests/schemas/test_metrics.py
  api/valor_api/backend/metrics/text_generation.py
  api/valor_api/enums.py
  api/valor_api/schemas/__init__.py
  api/valor_api/schemas/evaluation.py
  api/valor_api/schemas/metrics.py
Labels: improvement

#633 Increase code coverage to 90%
  api/tests/functional-tests/backend/core/test_llm_clients.py
  api/valor_api/backend/core/llm_clients.py
  api/valor_api/backend/metrics/text_generation.py
Labels: testing
